---
version: '3'
# Source: https://github.com/containers/podman/blob/v5.5.0/Makefile#L60
env:
  REMOTE_TAGS: remote exclude_graphdriver_btrfs btrfs_noversion containers_image_openpgp
tasks:
  default: {cmds: [{task: lint}, {task: test}, {task: build}], silent: true}
  lint:
    cmds: ['golint --fix', 'golangci-lint run --build-tags "$REMOTE_TAGS"']
    silent: true
  test:
    cmds: ['gotestsum --format standard-quiet -- -tags "$REMOTE_TAGS" ./...']
    silent: true
  build: {cmds: ['gobuild --all --build-tags "$REMOTE_TAGS"'], silent: true}
  update: {cmds: [goupdate], silent: true}
  update-library: {cmds: ['goupdate --exclusive funtimecoding'], silent: true}
  tool:
    cmds:
    - go install gotest.tools/gotestsum@latest
    - export GOPROXY=direct
    - go install github.com/funtimecoding/go-library/cmd/gobuild@latest
    - go install github.com/funtimecoding/go-library/cmd/golint@latest
    - go install github.com/funtimecoding/go-library/cmd/goupdate@latest
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.3.1
    silent: true
  install:
    cmds: ['gobuild --all --copy-to-bin --build-tags "$REMOTE_TAGS"']
    silent: true
  postgres:
    cmds: ['go run -tags "$REMOTE_TAGS" cmd/example/postgres/main.go']
    silent: true
  build-github:
    cmds: ['go build -v -tags "$REMOTE_TAGS" ./...']
    silent: true
  test-github:
    cmds: ['go test -v -tags "$REMOTE_TAGS" ./...']
    silent: true
